[project]
name = "aws-silicon-intel-lakehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.22",
    "structlog>=25.5.0",
]
