[project]
name = "aws-silicon-intel-lakehouse"
version = "0.1.0"
dependencies = [
    "boto3>=1.42.22",
    "pyspark>=4.1.0",
    "requests>=2.32.5",
    "structlog>=25.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/utils", "src/extract"]
