name: CI Data Lakehouse

on:
  push:
    branches: [main, feat/initial-setup]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linting Tools
        run: |
          pip install flake8 black

      - name: Check Python Syntax (Flake8)
        run: |
          # Falla si hay errores de sintaxis o variables no usadas
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Verify Terraform Format
        run: |
          terraform fmt -check -recursive infra/
