name: Infra Sanity Check

on:
  push:
    branches: [main, feat/initial-setup]
  pull_request:
    branches: [main]

jobs:
  validate-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: YAML Syntax Check
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: "{extends: default, rules: {line-length: disable}}"

      - name: Dockerfile Linter (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
